dataset: shapenet
# dataset_root: data/shapenet/processed_data.pkl
dataset_root: data/medshapenet/liver_dataset.pkl
num_tokens: 131
gradient_accumulation_steps: 32
batch_size: 8
block_size: 4608
padding: 0
scale_augment: true
scale_augment_val: false
shift_augment: true
shift_augment_val: false
wandb_main: true
suffix: ''
experiment: transformer_FT04379243
seed: 3
save_epoch: 1
sanity_steps: 0
val_check_percent: 1
val_check_interval: 8
resume: null
num_workers: 24
logger: wandb
overfit: false
num_val_samples: 4
max_val_tokens: 5000
top_k_tokens: 200
top_p: 0.9
temperature: 0.8
sequence_stride: 32
use_class_ids: false
use_smoothed_loss: true
use_point_feats: false
graph_conv: edge
g_no_max_pool: true
g_aggr: mean
ce_output: true
embed_dim: 384
n_embed: 4096
embed_loss_weight: 1.0
embed_levels: 4
tri_weight: 0.0
norm_weight: 0.0
area_weight: 0.0
angle_weight: 0.0
code_decay: 0.8
embed_share: false
use_multimodal_loss: false
vq_resume: pretrained/vocabulary/checkpoints/749-0.ckpt
ft_resume: pretrained/transformer_base/checkpoints/682-0.ckpt
ft_category: '04379243'
distribute_features: false
low_augment: false
model:
  in_emb: 3
  n_layer: 24
  n_head: 16
  n_embd: 768
  dropout: 0
  bias: false
lr: 0.0001
force_lr: null
max_epoch: 2400
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
warmup_steps: 100
min_lr: 6.0e-05
only_chairs: false
stochasticity: 0.1
